modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/HellFirePvP/AstralSorcery/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/astral-sorcery"
logoFile="logo.png"
credits="HellFirePvP (code), wiiv (models and textures), VulpTheHorseDog (models and textures)"
authors="HellFirePvP, wiiv, VulpTheHorseDog"
description='''Magic mod that draws power from stars and their constellations.'''

[[mixins]]
config="assets/astralsorcery/astralsorcery.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.astralsorcery]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.astralsorcery]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.astralsorcery]]
modId="observerlib"
type="required"
versionRange="[1.21.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.astralsorcery]]
modId="curios"
type="required"
versionRange="[9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.astralsorcery]]
modId="ponder"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="CLIENT"
